module.exports = exports = {
  vendors: [
    'immutable',
    'react',
    'react-redux',
    'react-router',
    'redux',
    'redux-devtools',
    'redux-devtools/lib/react',
  ],
  aliases: [
    'actions',
    'apis',
    'components',
    'constants',
    'containers',
    'entries',
    'dispatchers',
    'layouts',
    'models',
    'reducers',
    'routes',
    'services',
    'stores',
    'styles',
    'utils',
    'views',
  ],
};
